config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy] 

    def show
        
    end

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
        
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was created succesfully."
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
          
        if @article.update(article_params)
            flash[:notice] = "Article was updated succesfully."
            redirect_to @article
        else 
            render 'edit'
        end
    end

    def destroy
        
        @article.destroy
        redirect_to @article_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2> The following errors prevented the article from bieng saved </h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

    <p>
        <%= f.label :title %> </br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %> </br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1> Edit Article Page </h1>

<%= render 'form' %>

<button>
    <%= link_to 'Return to articles listing', articles_path %>
</button>

app/views/articles/index.html.erb
<h1> Articles Listening Page </h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan='3'>Actions</th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
        <tr>
            <td> <%= article.title %> </td>
            <td> <%= article.description %> </td>
            <td><%= link_to 'Show', article_path(article)  %></td>
            <td><%= link_to 'Edit', edit_article_path(article)  %></td>
            <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure !'}  %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<p>
    <button>
        <%= link_to 'Create new article', new_article_path %>
    </button>
    <button>
    <%= link_to 'Home Page', root_path %>
    </button>
</p>

app/views/articles/new.html.erb
<h1> Create a new Article </h1>

<%= render 'form' %>

<button>
    <%= link_to 'Return to articles listing', articles_path %>
</button>

app/views/articles/show.html.erb
<h1> Showing the Articles Details</h1>

<p><strong> Title </strong><%= @article.title %></p>
<p><strong> Description </strong><%= @article.description %></p>

<p>
    <button>
        <%= link_to 'Edit', edit_article_path(@article) %>
    </button>
    <button>
        <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure !'} %>
    </button>
    <button>
        <%= link_to 'Return to articles listing', articles_path %>
    </button>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %> 
    <%= msg %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    

    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> this is about page </h1>
<br>
<h1> ^_^ </h1>

<button>
    <%= link_to 'Home Page', root_path %>
</button>

app/views/pages/home.html.erb
<h1> Wellcome to Home Page </h1>

<button>
    <%= link_to 'Articles Listing', articles_path %>
</button>

<button>
    <%= link_to 'About Page', about_path %>
</button>
